spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/spring_cloud?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  application:
    name: product
env: eeeeeeeee
